name: Ruby on Rails CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.6

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Grant execute permission to bin/rubocop
      run: chmod +x bin/rubocop